name: Discord Notification on Push

on:
  push:
    branches:
      - main   # or whichever branch you want

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "📢 New commit pushed to the repository!"}' \
               $WEBHOOK_URL
