name: Discord Notification on Push

on:
  push:
    branches:
      - main   # change if needed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Embed Webhook
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "", 
                 "embeds": [
                   {
                     "title": "The List Has Been Updated!",
                     "description": "'"${{ github.event.head_commit.message }}"'",
                     "color": 5814783
                   }
                 ]
               }' \
               $WEBHOOK_URL
