name: Discord Notification on Push

on:
  push:
    branches:
      - main   # or whatever branch you want

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: dawidd6/action-send-discord-webhook@v3
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "📢 New commit pushed to the repository!"
